### ISSUE TITLE
Topo Metric Project

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/Program#12]
We're going to need some kind of a Topo Metrics project for Carol fairly Soon. 

### Questions to be answered?

* What level does it live at in the hierarchy? I'm going to suggest either by `Watershed` or one project at the Region level (All of CRB)
* We might eventually need to have this super level product incorporate the metrics from a TopoMetric AWS runner that runs dynamically but that will not be possible in a matter of weeks
* The product will consist of a SHP file with attributes for each metric. 
* One extra wrinkle is that there would be champ sites visible in a project then might be useful co-variants that are not champ metrics. 

### Tasks:

- [ ] **Carol** to supply NAR with the Access DB containing the correct metrics.
- [ ] **Philip** to write a tiny script to export metrics to a `CSV —> SHP` format 
- [ ] Mockup `project.rs.xml` XML that **Matt** will do with **Philip's** help
- [ ] **Philip** to generate and collect all the SHP files
- [ ] **Matt** or **Philip** to upload the projects into Riverscapes.

**Comment by philipbaileynar** [comment]
The extent is watershed, the resolution is "sites on network". I think that for now the Workbench can produce this project, including both the XML and also the Shapefile with attributes for each metric.

In the longer term, this project should be generated by AWS whenever visit level topo metrics are recalculated. Perhaps there is a lag, so that if dozens of visits within a watershed get their topo data updated within minutes of each other, then the watershed project is only regenerated 1 hour or so later (and not after each visit topo metrics is completed).

**Comment by volkcj** [comment]
How will aux and topo+aux metrics fit into this?  From the user's perspective, there is no distinction between topo, aux, and topo+aux metrics.  it's ok if we need to address the topo metrics as 'phase 1', but interim needs will need to also address 'all' metrics. I am happy to help.

**Comment by philipbaileynar** [comment]
Stale issue. Much progress on topo projects and also champ metric projects. Closing...
